apiVersion: v1
kind: Secret
metadata:
  name: taskflow-app-secret
  namespace: staging
type: Opaque
stringData:
  DATABASE_URL: postgresql://taskflow:taskflow@postgres:5432/taskflow
  JWT_SECRET: dev-secret
