apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-app-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: {{ .Values.environment | quote }}
  LOG_LEVEL: {{ .Values.logging.level | quote }}
  REDIS_URL: "redis://redis-master:6379"
  USER_SERVICE_URL: {{ .Values.services.userServiceUrl | quote }}
  TASK_SERVICE_URL: {{ .Values.services.taskServiceUrl | quote }}
  NOTIFICATION_SERVICE_URL: {{ .Values.services.notificationServiceUrl | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.endpoint | quote }}
  OTEL_EXPORT_INTERVAL_MS: {{ .Values.otel.exportIntervalMs | quote }}
