apiVersion: apps/{{.Chart.apiVersion}}
kind: Deployment
metadata:
  name: frontend
  namespace: {{.Values.Namespace}}
spec:
  replicas: {{.Values.frontend.replicaCount}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{.Values.image.frontend-prefix}}/taskflow-frontend:{{.Values.frontend.tag}}
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
